config/routes.rb
Rails.application.routes.draw do
  root controller: :pages, action: :index
  resources :pages, only: [:index]
  get :run_api, controller: :pages, action: :run_api
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
  end
  
  def run_api
    @params = params    
    start_date = Date.strptime(params[:start_date], "%Y-%m-%d").to_s
    end_date = Date.strptime(params[:end_date], "%Y-%m-%d").to_s
    group_by = params[:group_by]    
    if group_by.nil?
      raise 'Invalid Parameters'
    end
    group_by = group_by.join(',')
    #run the Reporting API script
    result = %x(ruby #{Rails.root.join 'app','scripts','api.rb'} #{start_date} #{end_date} #{group_by})
    flash.now[:success] = "File #{File.basename(result)} created successfully"
    render :index
    rescue 
      # rescue if any param is invalid
      flash.now[:danger] = 'Invalid Parameters'
      render :index    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_flash.html.haml
- flash.each do |message_type, message|
  - case message_type.to_sym
    - when :alert
      - message_type = :warning
    - when :notice
      - message_type = :info  
  .alert.alert-dismissible.fade.show#flash{ class: "alert-#{message_type}", role: :alert }
    %button.close{ type: :button, :'data-dismiss' => :alert, :'aria-label' => :Fechar }
      %span{ :'aria-hidden' => true } &times;
    - if message.class.to_s == 'Array'
      - message.each do |msg|
        = msg   
        %br       
    - else
      = message  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LucianoApiTask</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/flash' %>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.haml
.card{ style: 'width: 20rem; margin: auto auto' }
  %h4.card-header Luciano API Task
  = form_tag run_api_path, method: :get
  .form-group
    = label_tag :start_date
    = date_field_tag :start_date, Time.now.strftime("%Y-%m-%d"), class: 'form-control'
  .form-group  
    = label_tag :end_date
    = date_field_tag :end_date, Time.now.strftime("%Y-%m-%d"), class: 'form-control'
  .form-group  
    = label_tag :group_by
    %small.form-text.text.muted You can select multiple options
    = select_tag :group_by, options_for_select(['connection','app','platform','ad_type','ad_format','custom_1','custom_2','custom_3','custom_4','campaign','ad','ctm','country'].sort), multiple: true, class: 'form-control'
  .form-group  
    = submit_tag 'Run API', class: 'btn btn-primary btn-block'